"""add ale_kae and cpv

Revision ID: 1ef839728912
Revises: 5cc78c48c18a
Create Date: 2026-03-02 18:21:29.939961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef839728912'
down_revision = '5cc78c48c18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ale_kae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ale', sa.String(length=80), nullable=False),
    sa.Column('old_kae', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibility', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ale_kae', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ale_kae_ale'), ['ale'], unique=True)
        batch_op.create_index(batch_op.f('ix_ale_kae_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ale_kae_old_kae'), ['old_kae'], unique=False)

    op.create_table('cpv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpv', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cpv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cpv_cpv'), ['cpv'], unique=True)
        batch_op.create_index(batch_op.f('ix_cpv_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cpv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cpv_created_at'))
        batch_op.drop_index(batch_op.f('ix_cpv_cpv'))

    op.drop_table('cpv')
    with op.batch_alter_table('ale_kae', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ale_kae_old_kae'))
        batch_op.drop_index(batch_op.f('ix_ale_kae_created_at'))
        batch_op.drop_index(batch_op.f('ix_ale_kae_ale'))

    op.drop_table('ale_kae')
    # ### end Alembic commands ###
