"""add procurement invoice and receipt dates

Revision ID: 244f9dd84f0a
Revises: fcea1d175386
Create Date: 2026-03-08 13:50:14.436718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244f9dd84f0a'
down_revision = 'fcea1d175386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('invoice_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('materials_receipt_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('invoice_receipt_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_procurements_invoice_date'), ['invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_invoice_receipt_date'), ['invoice_receipt_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_materials_receipt_date'), ['materials_receipt_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurements_materials_receipt_date'))
        batch_op.drop_index(batch_op.f('ix_procurements_invoice_receipt_date'))
        batch_op.drop_index(batch_op.f('ix_procurements_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_procurements_invoice_date'))
        batch_op.drop_column('invoice_receipt_date')
        batch_op.drop_column('materials_receipt_date')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
