"""add supplier.doy

Revision ID: 3edda21bd0a1
Revises: db5e37c1095c
Create Date: 2026-03-05 18:31:38.502434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edda21bd0a1'
down_revision = 'db5e37c1095c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doy', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('doy')

    # ### end Alembic commands ###
