"""Add is_active to users

Revision ID: b8969c5e2ab4
Revises: 7d778253f937
Create Date: 2026-03-16 22:38:17.256643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8969c5e2ab4'
down_revision = '7d778253f937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
