"""add serviceunit address/phone and supplier email/emba

Revision ID: cdf26405abd5
Revises: 1ef839728912
Create Date: 2026-03-02 23:08:10.461680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf26405abd5'
down_revision = '1ef839728912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('emba', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('emba')
        batch_op.drop_column('email')

    with op.batch_alter_table('service_units', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
