"""initial

Revision ID: e53d04a2fa1d
Revises: 
Create Date: 2026-02-27 20:20:09.421497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53d04a2fa1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('option_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_categories_key'), ['key'], unique=True)

    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agm', sa.String(length=50), nullable=False),
    sa.Column('aem', sa.String(length=50), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('service_unit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_unit_id'], ['service_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personnel_aem'), ['aem'], unique=False)
        batch_op.create_index(batch_op.f('ix_personnel_agm'), ['agm'], unique=True)
        batch_op.create_index(batch_op.f('ix_personnel_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_personnel_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_personnel_service_unit_id'), ['service_unit_id'], unique=False)

    op.create_table('service_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('aahit', sa.String(length=100), nullable=True),
    sa.Column('commander', sa.String(length=255), nullable=True),
    sa.Column('curator', sa.String(length=255), nullable=True),
    sa.Column('supply_officer', sa.String(length=255), nullable=True),
    sa.Column('manager_personnel_id', sa.Integer(), nullable=True),
    sa.Column('deputy_personnel_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deputy_personnel_id'], ['personnel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_personnel_id'], ['personnel.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_units_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_units_deputy_personnel_id'), ['deputy_personnel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_units_manager_personnel_id'), ['manager_personnel_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('afm', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_afm'), ['afm'], unique=True)
        batch_op.create_index(batch_op.f('ix_suppliers_created_at'), ['created_at'], unique=False)

    op.create_table('option_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['option_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'value', name='uq_category_value')
    )
    with op.batch_alter_table('option_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_values_category_id'), ['category_id'], unique=False)

    op.create_table('procurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('service_unit_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('serial_no', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ale', sa.String(length=50), nullable=True),
    sa.Column('allocation', sa.String(length=80), nullable=True),
    sa.Column('quarterly', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('handler', sa.String(length=255), nullable=True),
    sa.Column('handler_personnel_id', sa.Integer(), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sum_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hop_commitment', sa.String(length=50), nullable=True),
    sa.Column('hop_forward1_commitment', sa.String(length=50), nullable=True),
    sa.Column('hop_forward2_commitment', sa.String(length=50), nullable=True),
    sa.Column('hop_preapproval', sa.String(length=50), nullable=True),
    sa.Column('hop_forward1_preapproval', sa.String(length=50), nullable=True),
    sa.Column('hop_forward2_preapproval', sa.String(length=50), nullable=True),
    sa.Column('hop_approval', sa.String(length=50), nullable=True),
    sa.Column('aay', sa.String(length=50), nullable=True),
    sa.Column('procurement_notes', sa.Text(), nullable=True),
    sa.Column('send_to_expenses', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['handler_personnel_id'], ['personnel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_unit_id'], ['service_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurements_aay'), ['aay'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_ale'), ['ale'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_allocation'), ['allocation'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_handler'), ['handler'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_handler_personnel_id'), ['handler_personnel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_hop_approval'), ['hop_approval'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_hop_commitment'), ['hop_commitment'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_hop_forward1_commitment'), ['hop_forward1_commitment'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_hop_forward1_preapproval'), ['hop_forward1_preapproval'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_hop_forward2_commitment'), ['hop_forward2_commitment'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_hop_forward2_preapproval'), ['hop_forward2_preapproval'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_hop_preapproval'), ['hop_preapproval'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_quarterly'), ['quarterly'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_send_to_expenses'), ['send_to_expenses'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_service_unit_id'), ['service_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurements_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('service_unit_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_unit_id'], ['service_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_personnel_id'), ['personnel_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_service_unit_id'), ['service_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username_snapshot', sa.String(length=150), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('related_procurement_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_procurement_id'], ['procurements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_related_procurement_id'), ['related_procurement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('material_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('is_service', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cpv', sa.String(length=50), nullable=True),
    sa.Column('nsn', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_lines_procurement_id'), ['procurement_id'], unique=False)

    op.create_table('procurement_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=80), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('offered_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procurement_id', 'supplier_id', name='uq_procurement_supplier')
    )
    with op.batch_alter_table('procurement_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurement_suppliers_procurement_id'), ['procurement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurement_suppliers_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurement_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_suppliers_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_procurement_suppliers_procurement_id'))

    op.drop_table('procurement_suppliers')
    with op.batch_alter_table('material_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_lines_procurement_id'))

    op.drop_table('material_lines')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_status'))
        batch_op.drop_index(batch_op.f('ix_feedback_related_procurement_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_created_at'))

    op.drop_table('feedback')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_service_unit_id'))
        batch_op.drop_index(batch_op.f('ix_users_personnel_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('procurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurements_status'))
        batch_op.drop_index(batch_op.f('ix_procurements_stage'))
        batch_op.drop_index(batch_op.f('ix_procurements_service_unit_id'))
        batch_op.drop_index(batch_op.f('ix_procurements_send_to_expenses'))
        batch_op.drop_index(batch_op.f('ix_procurements_quarterly'))
        batch_op.drop_index(batch_op.f('ix_procurements_hop_preapproval'))
        batch_op.drop_index(batch_op.f('ix_procurements_hop_forward2_preapproval'))
        batch_op.drop_index(batch_op.f('ix_procurements_hop_forward2_commitment'))
        batch_op.drop_index(batch_op.f('ix_procurements_hop_forward1_preapproval'))
        batch_op.drop_index(batch_op.f('ix_procurements_hop_forward1_commitment'))
        batch_op.drop_index(batch_op.f('ix_procurements_hop_commitment'))
        batch_op.drop_index(batch_op.f('ix_procurements_hop_approval'))
        batch_op.drop_index(batch_op.f('ix_procurements_handler_personnel_id'))
        batch_op.drop_index(batch_op.f('ix_procurements_handler'))
        batch_op.drop_index(batch_op.f('ix_procurements_fiscal_year'))
        batch_op.drop_index(batch_op.f('ix_procurements_created_at'))
        batch_op.drop_index(batch_op.f('ix_procurements_allocation'))
        batch_op.drop_index(batch_op.f('ix_procurements_ale'))
        batch_op.drop_index(batch_op.f('ix_procurements_aay'))

    op.drop_table('procurements')
    with op.batch_alter_table('option_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_values_category_id'))

    op.drop_table('option_values')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_created_at'))
        batch_op.drop_index(batch_op.f('ix_suppliers_afm'))

    op.drop_table('suppliers')
    with op.batch_alter_table('service_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_units_manager_personnel_id'))
        batch_op.drop_index(batch_op.f('ix_service_units_deputy_personnel_id'))
        batch_op.drop_index(batch_op.f('ix_service_units_created_at'))

    op.drop_table('service_units')
    with op.batch_alter_table('personnel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personnel_service_unit_id'))
        batch_op.drop_index(batch_op.f('ix_personnel_is_active'))
        batch_op.drop_index(batch_op.f('ix_personnel_created_at'))
        batch_op.drop_index(batch_op.f('ix_personnel_agm'))
        batch_op.drop_index(batch_op.f('ix_personnel_aem'))

    op.drop_table('personnel')
    with op.batch_alter_table('option_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_categories_key'))

    op.drop_table('option_categories')
    # ### end Alembic commands ###
